version: "3"
services:
  personal-site-strapi:
    container_name: personal-site-strapi
    build: .
    image: personal-site-strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: personal-site-strapiDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - personal-site-strapi
    depends_on:
      - personal-site-strapiDB

  personal-site-strapiDB:
    container_name: personal-site-strapiDB
    restart: unless-stopped
    env_file: .env
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - personal-site-strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - "5432:5432"
    networks:
      - personal-site-strapi

  personal-site-strapiAdminer:
    container_name: personal-site-strapiAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=personal-site-strapiDB
    networks:
      - personal-site-strapi
    depends_on:
      - personal-site-strapiDB

volumes:
  personal-site-strapi-data:

networks:
  personal-site-strapi:
    name: personal-site-strapi
    driver: bridge
